config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'bubbles#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # get "bubbles", to: "bubbles#index"
  # get "bubbles/:id", to: "bubbles#show", as: :bubble

  resources :bubbles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
end

app/models/bubble.rb
class Bubble < ApplicationRecord
    has_many :bookings
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
end

app/controllers/bubbles_controller.rb
class BubblesController < ApplicationController
    def index
      @bubbles = Bubble.all
    end

    def show
      @bubble = Bubble.find(params[:id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bubbles/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.buubble.com/wp-content/uploads/2020/05/A07I0591-uai-2560x1920.jpg);">
  <div class="container">
    <h1>Experience a weekend <strong>under the stars</strong> in a <strong>unique place</strong></h1>
    <p>Take a dip in nature and savor the present moment</p>
  </div>
</div>
<div class="card-trip" id="our_bubbles">
  <h1 class="category-title">Discover our bubbles</h1>
  <div class="card-trip-infos">
    <% @bubbles.each do |bubble| %>
      <div style="width: 350px; padding: 16px; box-shadow: 0 0 15px rgba(0,0,0,0.2)">
        <h1><%= link_to bubble.name,  controller: "bubbles", action: "show", id: bubble.id %></h1>
        <%= image_tag bubble.pictures, style:"width: 100%; height: 200px; object-fit: cover" %>
        <p><%= bubble.description %></p>
        <%= link_to "See availability", "#", class: "btn btn-ghost" %>
        </div>
    <% end %>
    </div>
  </div>
</div>
<div class="services">
  <h1 class="category-title">Our services</h1>
  <div class="container services-list">
    <div class="row">
      <div class="col services-details">
        <i class="fab fa-pagelines"></i>
        <h4>Service 1</h3>
        <p>Description</p>
      </div>
      <div class="col services-details">
        <i class="fab fa-pagelines"></i>
        <h4>Service 2</h3>
        <p>Description</p>
      </div>
      <div class="col services-details">
        <i class="fab fa-pagelines"></i>
        <h4>Service 3</h3>
        <p>Description</p>
      </div>
      <div class="col services-details">
        <i class="fab fa-pagelines"></i>
        <h4>Service 4</h3>
        <p>Description</p>
      </div>
    </div>
    <div class="row">
      <div class="col services-details">
        <i class="fab fa-pagelines"></i>
        <h4>Service 5</h3>
        <p>Description</p>
      </div>
      <div class="col services-details">
        <i class="fab fa-pagelines"></i>
        <h4>Service 6</h3>
        <p>Description</p>
      </div>
      <div class="col services-details">
        <i class="fab fa-pagelines"></i>
        <h4>Service 7</h3>
        <p>Description</p>
      </div>
      <div class="col services-details">
        <i class="fab fa-pagelines"></i>
        <h4>Service 8</h3>
        <p>Description</p>
      </div>
    </div>
  </div>
</div>

app/views/bubbles/show.html.erb
Test

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BubbleProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "bubbles#index", class: "navbar-brand" do %>
    <%= image_tag "https://www.bullesdesbois.fr/wp-content/uploads/2016/08/logo-bulles-des-bois-transparent.png", style: "width: 70px" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Our Domain", "#", class: "nav-link", style: "color: white" %>
        </li>
        <li class="nav-item">
          <%= link_to "Our Bubbles", "#{bubbles_path}#our_bubbles", class: "nav-link", style: "color: white" %>
        </li>
        <li class="nav-item">
          <%= link_to "Prices & Services", "#", class: "nav-link", style: "color: white" %>
        </li>
        <li class="nav-item">
          <%= link_to "To discover around", "#", class: "nav-link", style: "color: white" %>
        </li>
        <li class="nav-item">
          <%= link_to "Gift cards", "#", class: "nav-link", style: "color: white" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact", "#", class: "nav-link", style: "color: white" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>